### ISSUE TITLE
Add action buttons to report table

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl-ng#123]
Actions buttons for `kill` and `retry` (for both an analyzer and connector).

Part of https://github.com/intelowlproject/IntelOwl/issues/534

Context #101

**Comment by sp35** [comment]
![image](https://user-images.githubusercontent.com/51958314/127764079-9bf7246d-45e9-431b-907c-ec9b2c64ed44.png)
Kill - ![image](https://user-images.githubusercontent.com/51958314/127764239-a103f0da-7264-4ba9-a072-2dad6d43c27a.png)
Retry - ![image](https://user-images.githubusercontent.com/51958314/127764355-cdd7bb95-0ca1-433d-a7f4-d9c7baa4825e.png)

I have two options in mind:
- Two buttons on each row
  - Adds a new column `Actions`. 
  - The buttons will be disabled if invalid for action, so no validation needs to be shown.
  - Con: large no of records, but it should also be considered that only running/pending plugins can be killed, similarly for retry.
 
- Two buttons on top of the table
  - This is a standard option used for large records. 
  - This would require changes in the endpoints to accept multiple plugins and handling which sub-requests failed in a single request made.
  - Checkbox for each row, selected ones can be chosen for action.
  - Validation can be shown using a hover message (on the action button) if invalid records have been chosen.

I think the first one is still a reasonable choice as these actions by nature aren't bulk specific, but I'm open to suggestions.

**Comment by mlodic** [comment]
good argumentation. I agree with your analysis. For this case, maybe it is simpler to choose the first option

**Comment by sp35** [comment]
This can be closed now.
