### ISSUE TITLE
Adjust connectors management in sidebar

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl-ng#128]
Pending

![image](https://user-images.githubusercontent.com/51958314/128235086-dbfabaaf-02f0-4971-abb4-961ed2a2071f.png)

**Comment by Eshaan7** [comment]
We do not really require an extra icon.

![image](https://user-images.githubusercontent.com/16389167/128319672-02fd8536-48d7-49ed-817d-1db1bfc3646f.png)



Move the `Connectors Management` between `Analyzers Management` and `Scans Management` and rename `Connectors` to `Table View` with the same icon that is used in `Analyzers Management`.
