### ISSUE TITLE
TLP Configuration Labels Overlap Radio Buttons

### ISSUE THREAD

**Issue by JasonFritsche** [intelowlproject/IntelOwl-ng#158]
The TLP Configuration Labels overlap the radio buttons. There should be adequate spacing/style change to prevent the overlap.
This issue seems to be caused by the nebular sidebar component.
![tlplabels](https://user-images.githubusercontent.com/34847680/135541949-bf76c8bd-fe37-400b-b05a-94dea02e7dcd.png)

I would like to work on this issue. Please assign and give any guidance/suggestions on how the issue should be resolved.

**Comment by eshaan7** [comment]
Hi, @JasonFritsche. We appreciate your interest in contributing to IntelOwl and thank you for the bug report !

This required only a small change so I've fixed it before I make the new release. But if you are still interested, you can still contribute to the project in other ways! (See: #86 and #104)
