### ISSUE TITLE
Redirect "/" to the Dashboard when logged

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl-ng#27]
At the moment, if we are logged or not, when we navigate to the root URL we are being redirected to the login interface. In the case we are already logged, we should be redirected to the Dashboard instead

**Comment by Eshaan7** [comment]
I think this is a side-effect of using SessionAuthentication because atm the angular client is configured to work with tokens. This would be taken into account when we configure angular to use SessionAuthentication and drop nebular's token based auth
