### ISSUE TITLE
Adjusts on "Table tree"

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl-ng#28]
in the "Table tree", `external_service` and `leaks_info` boolean could contain a little tooltip to explain what do they mean. 
Also, I would show a proper icon when the flag is not set instead of "N/A" because, in this case, it is like a "No". Maybe we can use the same icon used for failed analysis.
Last, the search "Yes/No" does not work properly.

**Comment by mlodic** [comment]
Other clarity changes ideas:

- in "supports" we could remove the "code visualization" of the list (bracket,quotes) and just show "ip, domain" for example.
- "config params" could not be clear by a user perspective. This is because a new user could think that only the ones with this dictionary populated have to be configured while this is not the purpose of this field. For this purpose I would:
* change the visualization name to "additional config" or something similar
* do not show this column by default and let the user click a button to expand this in case he wants to view it. Otherwise we can put it just as the last column (far right) because less important.
* populate a new boolean parameter in `analyzer_config.json` called "requires_configuration" (I am about to add this to all the analyzers) and show it as a new column

**Comment by Eshaan7** [comment]
commit - https://github.com/intelowlproject/IntelOwl-ng/commit/7c8bf66b8fae5a307459f7489fd4a7910c21e903
