### ISSUE TITLE
Research a more user-friendly visualization for the Job Results.

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl-ng#29]
There are 2 different views of an analyzer result:
* table one, integrated with the web interface style
* raw one, classic navigable JSON

I noticed that in the case of a very long result for an analyzer (try VT analyzer or OTX),  the first view could become completely unreadable. In particular it is bad when there are a lot of dictionaries inside other dictionaries inside other dictionaries and so on. I think that we could try to keep the "raw" one because it always worth, in particular for debugging, while we could try to let the "table" one more user-friendly. Maybe, by default, we can only show the first keys of the dict and then we let the user choose by clicking which one he wants to expand and see more.

Waiting for your feedback and your proposals about this

**Comment by Eshaan7** [comment]
I agree that given a JSON object with too many nested fields breaks the carded tabular view. But in any case we always have the navigable JSON or the ability to view raw JSON document so I'd say this is not top priority at the moment.

> Maybe, by default, we can only show the first keys of the dict and then we let the user choose by clicking which one he wants to expand and see more.

Good idea! I will research how we could use an accordion for this.
