### ISSUE TITLE
Job delete button

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl-ng#69]
> We could provide an API + a button in the GUI to allow the user to perform this operation directly. This should be added in:
> 
>1. The single job view
>2. The dashboard

_Originally posted by @Eshaan7 in https://github.com/intelowlproject/IntelOwl/issues/324#issuecomment-767705563_

**Comment by Meghana-12** [comment]
Hey, I'd like to try this, could you assign this to me ?

**Comment by mlodic** [comment]
welcome @Meghana-12! happy yo have you here

**Comment by Meghana-12** [comment]
Hey, is there a design i need to follow while creating the component ?

**Comment by Eshaan7** [comment]
> Hey, is there a design i need to follow while creating the component ?

We are using the Nebular component library (https://akveo.github.io/nebular/). Other than that, just basic angular stuff. Like the AJAX for the DELETE should be made part of HTTP service and then the API call made part of Job service which is then called via the component when user clicks on delete button.

**Comment by Meghana-12** [comment]
Oh, thanks! I'll go through that. And where should I place the button in the given pages?

**Comment by Eshaan7** [comment]
> Oh, thanks! I'll go through that. And where should I place the button in the given pages? 

Place it on the left of the view-raw-json button.

**Comment by Meghana-12** [comment]
Sure, I'll do that then.
