### ISSUE TITLE
context menu for job actions (resuable component)

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl-ng#71]
Should create a reusable component for the job actions like `delete`, `kill`, `download job sample`, `view raw json` (maybe not all) .

Component design: [context menu](https://akveo.github.io/nebular/docs/components/context-menu/overview#nbcontextmenudirective) or [actions](https://akveo.github.io/nebular/docs/components/actions/overview#nbactionscomponent).

The idea is we should be able to use this same component in the dashboard as well as job result page.

**Comment by Eshaan7** [comment]
Assigned to @m0mosenpai.

**Comment by m0mosenpai** [comment]
Are there any starting points/ things I should be aware of, is possible ? It'll be my first time working on the frontend..

**Comment by Eshaan7** [comment]
We should create a new component called JobActionsMenuComponent that has
the buttons such as delete job, kill job, download raw JSON, download
sample (same as the ones available in the job result page). You basically
have to extract these buttons from the job result component to an
individual component that can be reused.
