### ISSUE TITLE
Understanding which analyzers are running

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl-ng#94]
![image](https://user-images.githubusercontent.com/30625432/114842932-9c428000-9dd9-11eb-87df-d2f0f0e11b99.png)

There could be the case when there are some analyzers that do not finish fast.
The result could be that a user is waiting for those analyzers but cannot understand *which* ones are still running because there is nothing that tells him this in the GUI. As you can see in the example, it just tells you the number of completed / number of total analyzers to be executed.

At the moment, the analysis report page is updated every x seconds with the values of the analyzers that terminated the execution in a failed or successful way.
One idea could be to show *every* analyzer since the start of the very analysis and, every x seconds, update the status like before but reordering the list by setting:
* successful ones at top
* failed ones after
* still running ones at the end (with a new icon different from the others 2)

![image](https://user-images.githubusercontent.com/30625432/114843692-5f2abd80-9dda-11eb-8725-8d73ade1e07d.png)

**Comment by m0mosenpai** [comment]
![image](https://user-images.githubusercontent.com/17424778/114867928-fc094d00-9e12-11eb-909e-d1649bcd633a.png)
We can maybe reuse this loading icon to show the running analyzers

**Comment by sp35** [comment]
![image](https://user-images.githubusercontent.com/51958314/128236285-777f29d5-a360-4ae7-9502-4c40eee520be.png).
The way we handle the plugin reports now (storing reports in the database), this issue is fixed.

side note: `completed` word may appear a bit ambiguous as it's `no of reports in the table / no of analyzers to execute` now.

**Comment by mlodic** [comment]
is not possible to still use the `number of completed / number of total analyzers to be executed` there?

**Comment by Eshaan7** [comment]
> is not possible to still use the `number of completed / number of total analyzers to be executed` there?

It should be possible to do this.

IMO, there are just 2 more improvements we can make here:
- [ ] Show both `number of completed / number of total analyzers to be executed` and also `no of analyzers started / no of analyzers to execute`. So, it looks like:

```css
Started: 11/12, Running: 2/12
```

- [ ] Default sorting should be applied to the analyzers/connectors table in the sense that it has,

> successful ones at top
> failed ones after
> still running ones at the end (with a new icon different from the others 2)
